{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gyre.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gyre.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - secrets
  verbs: ["create"]
- apiGroups: [""]
  resources:
    - secrets
  resourceNames:
    - {{ .Values.admin.secretName }}
    - {{ include "gyre.fullname" . }}-encryption
  verbs: ["get", "list", "watch", "update", "patch"]
{{- end }}
