{{- if and (not .Values.encryption.existingSecret) (or .Values.encryption.gyreKey .Values.encryption.authKey) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gyre.fullname" . }}-encryption
  namespace: {{ .Release.Namespace }}
  annotations:
    # Retain this Secret on helm uninstall to prevent losing encryption keys.
    # Delete manually when you are certain the keys are no longer needed.
    helm.sh/resource-policy: keep
  labels:
    {{- include "gyre.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.encryption.gyreKey }}
  GYRE_ENCRYPTION_KEY: {{ .Values.encryption.gyreKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.encryption.authKey }}
  AUTH_ENCRYPTION_KEY: {{ .Values.encryption.authKey | b64enc | quote }}
  {{- end }}
{{- end }}
