import crypto from 'node:crypto';

/**
 * PKCE (Proof Key for Code Exchange) utilities for OAuth2 authorization code flow.
 * See RFC 7636: https://tools.ietf.org/html/rfc7636
 *
 * PKCE adds security to the OAuth2 authorization code flow by:
 * 1. Generating a random code_verifier
 * 2. Creating a code_challenge = SHA256(code_verifier)
 * 3. Sending code_challenge in authorization request
 * 4. Sending code_verifier in token exchange request
 * 5. Server verifies: SHA256(code_verifier) == code_challenge
 *
 * This prevents authorization code interception attacks.
 */

/**
 * Generate a random state parameter for CSRF protection.
 * The state parameter should be unique per authorization request
 * and validated when the user returns from the IdP.
 *
 * @returns 64-character hex string (32 random bytes)
 */
export function generateState(): string {
	return crypto.randomBytes(32).toString('hex');
}

/**
 * Generate a PKCE code verifier.
 * Must be a cryptographically random string using characters [A-Z] / [a-z] / [0-9] / "-" / "." / "_" / "~"
 * Length: 43-128 characters (RFC 7636)
 *
 * We use base64url encoding which naturally produces valid characters.
 *
 * @param length - Length in characters (43-128). Default: 43 (minimum recommended)
 * @returns URL-safe base64 string suitable as code_verifier
 */
export function generateCodeVerifier(length: number = 43): string {
	if (length < 43 || length > 128) {
		throw new Error('PKCE code_verifier length must be between 43 and 128 characters');
	}

	// Generate random bytes
	// base64url encoding expands bytes by ~4/3, so we need length * 3/4 bytes
	const numBytes = Math.ceil((length * 3) / 4);
	const verifier = crypto.randomBytes(numBytes).toString('base64url');

	// Truncate to exact length
	return verifier.substring(0, length);
}

/**
 * Generate a PKCE code challenge from a code verifier.
 * Uses SHA256 hash with base64url encoding (method = S256).
 *
 * @param codeVerifier - The code verifier generated by generateCodeVerifier()
 * @returns URL-safe base64 string suitable as code_challenge
 */
export function generateCodeChallenge(codeVerifier: string): string {
	return crypto.createHash('sha256').update(codeVerifier).digest('base64url');
}
