import crypto from 'node:crypto';

/**
 * PKCE (Proof Key for Code Exchange) utilities for OAuth2 authorization code flow.
 * See RFC 7636: https://tools.ietf.org/html/rfc7636
 *
 * PKCE adds security to the OAuth2 authorization code flow by:
 * 1. Generating a random code_verifier
 * 2. Creating a code_challenge = SHA256(code_verifier)
 * 3. Sending code_challenge in authorization request
 * 4. Sending code_verifier in token exchange request
 * 5. Server verifies: SHA256(code_verifier) == code_challenge
 *
 * This prevents authorization code interception attacks.
 */

/**
 * Generate a random state parameter for CSRF protection.
 * The state parameter should be unique per authorization request
 * and validated when the user returns from the IdP.
 *
 * @returns 64-character hex string (32 random bytes)
 */
export function generateState(): string {
	return crypto.randomBytes(32).toString('hex');
}

/**
 * Generate a PKCE code verifier.
 * Must be a cryptographically random string using characters [A-Z] / [a-z] / [0-9] / "-" / "." / "_" / "~"
 * Length: 43-128 characters (RFC 7636)
 *
 * We use base64url encoding which naturally produces valid characters.
 *
 * @param length - Length in characters (43-128). Default: 43 (minimum recommended)
 * @returns URL-safe base64 string suitable as code_verifier
 */
export function generateCodeVerifier(length: number = 43): string {
	if (length < 43 || length > 128) {
		throw new Error('PKCE code_verifier length must be between 43 and 128 characters');
	}

	// Generate random bytes
	// base64url encoding expands bytes by ~4/3, so we need length * 3/4 bytes
	const numBytes = Math.ceil((length * 3) / 4);
	const verifier = crypto.randomBytes(numBytes).toString('base64url');

	// Truncate to exact length
	return verifier.substring(0, length);
}

/**
 * Generate a PKCE code challenge from a code verifier.
 * Uses SHA256 hash with base64url encoding (method = S256).
 *
 * @param codeVerifier - The code verifier generated by generateCodeVerifier()
 * @returns URL-safe base64 string suitable as code_challenge
 */
export function generateCodeChallenge(codeVerifier: string): string {
	return crypto.createHash('sha256').update(codeVerifier).digest('base64url');
}

/**
 * Verify a code verifier against a code challenge.
 * Used server-side to validate PKCE flow (though we're the client, this is useful for testing).
 *
 * @param codeVerifier - The code verifier to test
 * @param codeChallenge - The code challenge to verify against
 * @returns true if code_challenge == SHA256(code_verifier)
 */
export function verifyCodeChallenge(codeVerifier: string, codeChallenge: string): boolean {
	const computedChallenge = generateCodeChallenge(codeVerifier);
	return computedChallenge === codeChallenge;
}

/**
 * Generate both verifier and challenge in one call.
 * Useful for starting the OAuth2 flow.
 *
 * @returns Object with verifier and challenge
 */
export function generatePKCEPair(): { verifier: string; challenge: string } {
	const verifier = generateCodeVerifier();
	const challenge = generateCodeChallenge(verifier);
	return { verifier, challenge };
}

/**
 * Validate PKCE parameters for correctness.
 * Useful for input validation.
 */
export function validatePKCEParams(params: {
	verifier?: string;
	challenge?: string;
}): { valid: boolean; error?: string } {
	const { verifier, challenge } = params;

	if (verifier !== undefined) {
		if (verifier.length < 43 || verifier.length > 128) {
			return {
				valid: false,
				error: 'Code verifier length must be between 43 and 128 characters'
			};
		}

		// Check for valid base64url characters
		if (!/^[A-Za-z0-9_-]+$/.test(verifier)) {
			return {
				valid: false,
				error: 'Code verifier contains invalid characters (must be base64url)'
			};
		}
	}

	if (challenge !== undefined) {
		// Code challenge should be 43 characters for SHA256 base64url
		if (challenge.length !== 43) {
			return {
				valid: false,
				error: 'Code challenge should be 43 characters for SHA256'
			};
		}

		// Check for valid base64url characters
		if (!/^[A-Za-z0-9_-]+$/.test(challenge)) {
			return {
				valid: false,
				error: 'Code challenge contains invalid characters (must be base64url)'
			};
		}
	}

	return { valid: true };
}
